const START_DIFFICULTY = 3;
const START_REWARD_COINS = 10000;
const START_AWARD_COINS = 2;
const BLOCK_GENERATION_INTERVAL = 10;
const DIFFICULTY_ADJUSTMENT_INTERVAL = 10;

module.exports = {
  START_DIFFICULTY,
  START_AWARD_COINS,
  START_REWARD_COINS,
  BLOCK_GENERATION_INTERVAL,
  DIFFICULTY_ADJUSTMENT_INTERVAL,
};
